@startuml

actor "User" as user

node "Authentication" {
    component "Login" as login
    component "SignUp" as signup
}

node "Kotlin RESTful API" {
    component "Controller" as controller
    component "Service" as service
    component "Repository" as repository
}

database "MySQL" as database

user <--> login
user <--> signup
login <--> controller
controller <--> service
service <--> repository
repository <--> database

@enduml
